networks:
  application:
    name: ${NETWORK_APPLICATION}
    driver: bridge
  proxy:
    name: proxy
    ipam:
      config:
        - subnet: 172.30.0.0/24
volumes:
  postgres_data:
    name: postgres_data
    driver_opts:
      type: none
      device: ${POSTGRES_VOLUME}/data
      o: bind
  go-mod-cache:
  go-build-cache: