{
 "title": "Table Health Copy",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Resumen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Número de tablas monitoreadas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_stat_user_tables_n_live_tup)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Live Tuples",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_user_tables_n_live_tup)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Dead Tuples",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_user_tables_n_dead_tup)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Dead Tuples",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(pg_stat_user_tables_n_dead_tup) / (sum(pg_stat_user_tables_n_live_tup)+sum(pg_stat_user_tables_n_dead_tup))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tablas más grandes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Live Tuples",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n10,\npg_stat_user_tables_n_live_tup\n)",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Dead Tuples",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n10,\npg_stat_user_tables_n_dead_tup\n)",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  { "title": "Actividad", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Sequential Scan",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n10,\nrate(pg_stat_user_tables_seq_scan[5m])\n)",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Index Scan",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n10,\nrate(pg_stat_user_tables_idx_scan[5m])\n)",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  { "title": "Vacuum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Vacuum Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n10,\ntable_vacuum_health_vacuum_count\n)",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Autovacuum Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n10,\ntable_vacuum_health_autovacuum_count\n)",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Dead Tuples %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\ntable_vacuum_health_n_dead_tup\n/\n(\ntable_vacuum_health_n_live_tup\n+\ntable_vacuum_health_n_dead_tup\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}