{
 "title": "03-vacuum",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(pg_stat_user_tables_n_live_tup, instance)"
    }
   },
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "label_values(pg_stat_user_tables_n_live_tup, datname)"
    }
   },
   {
    "name": "schema",
    "label": "schema",
    "query": {
     "query": "label_values(pg_stat_user_tables_n_live_tup{instance=\"$instance\",datname=\"$database\"}, schemaname)"
    }
   },
   {
    "name": "table",
    "label": "table",
    "query": {
     "query": "label_values(pg_stat_user_tables_n_live_tup{instance=\"$instance\",datname=\"$database\",schemaname=\"$schema\"}, relname)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Vacuum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dead Tuples",
   "type": "table",
   "description": "Mostrar tablas con más tuplas muertas.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_dead_tup{schemaname=\"$schema\"}",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Dead Tuple Ratio",
   "type": "table",
   "description": "Detectar tablas con alto porcentaje de basura.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "100 * pg_stat_user_tables_n_dead_tup{schemaname=\"$schema\"} / (pg_stat_user_tables_n_live_tup{schemaname=\"$schema\"} + pg_stat_user_tables_n_dead_tup{schemaname=\"$schema\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Vacuum",
   "type": "table",
   "description": "Ver último VACUUM manual.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_last_vacuum{schemaname=\"$schema\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Autovacuum",
   "type": "table",
   "description": "Ver última ejecución automática.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_last_autovacuum{schemaname=\"$schema\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Analyze",
   "type": "table",
   "description": "Ver último ANALYZE manual.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_last_analyze{schemaname=\"$schema\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last AutoAnalyze",
   "type": "table",
   "description": "Ver última actualización automática de estadísticas.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_last_autoanalyze{schemaname=\"$schema\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vacuum Count",
   "type": "table",
   "description": "Número de VACUUM manuales.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_vacuum_count{schemaname=\"$schema\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Autovacuum Count",
   "type": "table",
   "description": "Número de autovacuums.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_autovacuum_count{schemaname=\"$schema\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analyze Count",
   "type": "table",
   "description": "Número de ANALYZE manuales.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_analyze_count{schemaname=\"$schema\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AutoAnalyze Count",
   "type": "table",
   "description": "Número de autoanalyze.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_autoanalyze_count{schemaname=\"$schema\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dead Tuples Evolution",
   "type": "table",
   "description": "Evolución de tuplas muertas.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_dead_tup{schemaname=\"$schema\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Autovacuum Activity",
   "type": "table",
   "description": "Actividad diaria del autovacuum.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "increase(pg_stat_user_tables_autovacuum_count{schemaname=\"$schema\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vacuum Activity",
   "type": "table",
   "description": "Actividad de VACUUM manual.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "increase(pg_stat_user_tables_vacuum_count{schemaname=\"$schema\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analyze Activity",
   "type": "table",
   "description": "Frecuencia de actualización de estadísticas.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "increase(pg_stat_user_tables_autoanalyze_count{schemaname=\"$schema\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}